module:
  hugoVersion:
    extended: true
    min: 0.41.0
markup:
  goldmark:
    parser:
      attribute:
        block: true
        title: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: rrt
    tabWidth: 4
  tableOfContents:
    startLevel: 2
    endLevel: 3
    ordered: false
params:
  theme_config:
    appearance: auto
    back_home_text: "Home"
    back_previous_text: "Back"
    date_format: "2006/01/02"
    isListGroupByDate: true
    isShowFooter: true
